// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMOyQYLFVLPG-piHOH2dKzg0qg2u5-YJI',
    appId: '1:735495916641:web:dcadd9bfa4f214eb56ee20',
    messagingSenderId: '735495916641',
    projectId: 'propup-715a1',
    authDomain: 'propup-715a1.firebaseapp.com',
    storageBucket: 'propup-715a1.appspot.com',
    measurementId: 'G-DKNNQ4902R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYm97SGRA-Pykjt_x0Jlz7PDmYKdKUlBo',
    appId: '1:735495916641:android:b790310cd769e75556ee20',
    messagingSenderId: '735495916641',
    projectId: 'propup-715a1',
    storageBucket: 'propup-715a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL6Ly1zPi97lfnYfklya4m_OE2ijRWOG8',
    appId: '1:735495916641:ios:150b6c02eab4f92156ee20',
    messagingSenderId: '735495916641',
    projectId: 'propup-715a1',
    storageBucket: 'propup-715a1.appspot.com',
    iosClientId: '735495916641-j11nb1r5qknf4e2tmv9dag0fqklg5nuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.propup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL6Ly1zPi97lfnYfklya4m_OE2ijRWOG8',
    appId: '1:735495916641:ios:bbbdf9015c9bda4456ee20',
    messagingSenderId: '735495916641',
    projectId: 'propup-715a1',
    storageBucket: 'propup-715a1.appspot.com',
    iosClientId: '735495916641-o0l3bfnikatf3tef31arcahip70svmir.apps.googleusercontent.com',
    iosBundleId: 'com.example.propup.RunnerTests',
  );
}
